### ISSUE TITLE
fix: I cant edit or move ideas in the "my ideas" page

### ISSUE THREAD

**Issue by LetsPoke** [knoffhoff/hms#1335]

**Comment by rz-p** [comment]
Quick question regarding `IdeaDetails.tsx` @LetsPoke 

Does every idea card has an assigned default type or it can be assigned multiple types?

**Comment by LetsPoke** [comment]
yeah its always 1 Type 
and if I remember correctly the type defines the context in which the idea is shown
for example if the idea is loaded in the ideation portal then the type is set to ideation portal

**Comment by rz-p** [comment]
Does the type also cascades? I see there are many `&&` and `||` arguments and when I changed some of it, elements from other types also shows up
