### ISSUE TITLE
fix: Idea creation date will reset if filter is applied

### ISSUE THREAD

**Issue by rz-p** [knoffhoff/hms#1491]
When clicking the show my ideas checkbox, the creation will change
(on working tree #1475, not visible on main) 

[**Video here**](https://idealo-my.sharepoint.com/:v:/g/personal/rizki_pramadhan_idealo_de/ETvX_PUNGgVIpdjyz-cKp1UBGoqaXdEaJYa886XzQ7Mfeg?e=aFmljm)

**Comment by LetsPoke** [comment]
are you sure about that or is it because your own ideas got created today?

**Comment by rz-p** [comment]
could be, but we'll have to check further

**Comment by LetsPoke** [comment]
ah in your video you showing the searchbar not the my ideas filter checkbox right?
