### ISSUE TITLE
BA: Redesign the Idea Buttons

### ISSUE THREAD

**Issue by LetsPoke** [knoffhoff/hms#1498]
Right now we have the 4 idea buttons: 
Delete, Edit, Upload Video and Move Idea in the Color: 
Red, Blue, Green and Yellow 

Some people misstake the buttons for Labels as they are so colorfull and all have the same size 
We should rethink and redesign this 4 buttons so that they look more like buttons and have some kind of hierarchy between them

**Comment by reyhanrumengan** [comment]
TODO:

- [ ] Join Idea: Toggle Button. Still need to think, where to put better
- [ ] Voting: Up/Down Arrow. Maybe will be place beside the voting counter

- [ ] Add new section under Comment Section for Delete, Edit, Upload VIdeo, Move Idea
- [ ] Delete Button: add trash icon / replace with trash icon (?)
- Change Color (?): 
- [ ] Edit Button
- [ ] Upload Video
- [ ] Move Idea

**Comment by reyhanrumengan** [comment]
Design in Miro Board 
[](https://miro.com/app/board/uXjVOCwjacs=/?moveToWidget=3458764556977448075&cot=14)
