### ISSUE TITLE
bug: after delete idea in all ideas, the deleted idea card still there

### ISSUE THREAD

**Issue by reyhanrumengan** [knoffhoff/hms#1536]
after delete idea, the idea card not removed and it just became a blank card

![Bildschirmfoto 2023-06-20 um 13 14 46](https://github.com/knoffhoff/hms/assets/25485002/d1f6ee37-b276-4e06-9e9d-027ca4b7986f)

**Comment by rz-p** [comment]
is it on main? @reyhanrumengan

**Comment by rz-p** [comment]
Fixed by commit `cce7387` on main branch (by accident)
