### ISSUE TITLE
join or leave hackathon functionality

### ISSUE THREAD

**Issue by jakepanter** [knoffhoff/hms#433]
- notification works but it is not yet reflected in the backend
- on reload the state is as before

**Comment by LetsPoke** [comment]
<img width="1265" alt="Bildschirmfoto 2022-07-06 um 09 20 26" src="https://user-images.githubusercontent.com/59581396/177492793-1552b61a-9835-47a1-9554-65c7e8a2cf15.png">

just to save somewhere

**Comment by LetsPoke** [comment]
<img width="548" alt="Bildschirmfoto 2022-07-06 um 09 23 25" src="https://user-images.githubusercontent.com/59581396/177493294-d4276a9d-1504-427e-a9d7-637292b9f527.png">

user with id is not a participant anymore, so problem is probably somewhere in the backend?

**Comment by LetsPoke** [comment]
<img width="1356" alt="Bildschirmfoto 2022-07-06 um 09 26 40" src="https://user-images.githubusercontent.com/59581396/177493861-72edc18f-7cbb-480a-b846-e71e49566367.png">

user is also not participant in the frontend anymore

**Comment by LetsPoke** [comment]
<img width="1356" alt="Bildschirmfoto 2022-07-06 um 10 21 40" src="https://user-images.githubusercontent.com/59581396/177504723-cdf870f2-98cf-41c4-b598-bdeca2412c35.png">

looks like it got not completly deleted
